name: "Team Sync"

on:
  push:
    branches:
      - master

jobs:
  team_sync:
    name: Team Sync
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        env:
          COMMUNITY_GITHUB_OWNER: beyondstorage
          COMMUNITY_GITHUB_ACCESS_TOKEN: ${{ secrets.COMMUNITY_GITHUB_ACCESS_TOKEN }}
        run: go run github.com/beyondstorage/go-community/cmd/community team sync
