name: "Team Sync"

on:
  push:
    branches:
      - master

jobs:
  team_sync:
    name: Team Sync
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup community tools
        env:
          COMMUNITY_VERSION: 0.1.0
        run: curl -sSL "https://github.com/beyondstorage/go-community/releases/download/${COMMUNITY_VERSION}/community_${COMMUNITY_VERSION}_linux_arm64.tar.gz" -O community.tar.gz && tar -xvf community.tar.gz && ./community --help

      - name: Sync Team
        env:
          COMMUNITY_GITHUB_OWNER: beyondstorage
          COMMUNITY_GITHUB_ACCESS_TOKEN: ${{ secrets.COMMUNITY_GITHUB_ACCESS_TOKEN }}
        run: ./community team sync
